### ISSUE TITLE
Update example with Babel

### ISSUE THREAD

**Issue by fabarea** [Couto/babel-runners-example#1]
I found this repo as a great source of inspiration, thanks! Meanwhile 6to5 has [been renamed to Babel](https://babeljs.io/blog/2015/02/15/not-born-to-die/). It would be great if you could update your example. I wasn't quite able to make it work with the new product name.

**Comment by couto** [comment]
Ahah, this repo was made for me to test runners and compare outputs, while I was writing the babel-loader (6to5 at the time) so I never considered it as a project.

Still, fair point. I will try to update later tonight! :)

**Comment by fabarea** [comment]
Would be awesome!

**Comment by fabarea** [comment]
:)
